# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'translation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11translation.proto\x12\ndoccreator\"9\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\"!\n\x11TranslateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2^\n\x12TranslationService\x12H\n\tTranslate\x12\x1c.doccreator.TranslateRequest\x1a\x1d.doccreator.TranslateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=33
  _globals['_TRANSLATEREQUEST']._serialized_end=90
  _globals['_TRANSLATERESPONSE']._serialized_start=92
  _globals['_TRANSLATERESPONSE']._serialized_end=125
  _globals['_TRANSLATIONSERVICE']._serialized_start=127
  _globals['_TRANSLATIONSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
