# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\ndoccreator\")\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\"\x1c\n\x0bTTSResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32K\n\nTTSService\x12=\n\nSynthesize\x12\x16.doccreator.TTSRequest\x1a\x17.doccreator.TTSResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=25
  _globals['_TTSREQUEST']._serialized_end=66
  _globals['_TTSRESPONSE']._serialized_start=68
  _globals['_TTSRESPONSE']._serialized_end=96
  _globals['_TTSSERVICE']._serialized_start=98
  _globals['_TTSSERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
